flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/tree.gltf  # For AR
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: fonts/NotoSansArabic-Regular.ttf