name: couldai_user_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0

  # State Management & Storage
  shared_preferences: ^2.2.3

  # Maps
  mapbox_gl: ^0.16.0

  # AR
  ar_flutter_plugin: ^0.7.3

  # Voice Assistant
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2

  # PDF Generation
  pdf: ^3.10.8
  path_provider: ^2.1.3

  # Internationalization
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/tree.gltf # For AR
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: fonts/NotoSansArabic-Regular.ttf
